language: php

php: 5.3.3

env:
    - SYMFONY_FORM_VERSION="2.3.*"
    - SYMFONY_FORM_VERSION="2.4.*"

before_script:
    - composer require --no-update symfony/form:${SYMFONY_FORM_VERSION}
    - composer install --prefer-source

script: bin/phpunit

branches:
    only: master

notifications:
    email: geloen.eric@gmail.com
